import Link from "next/link";
import { SiteFooter } from "@/components/site/site-footer";
import { SiteHeader } from "@/components/site/site-header";

const benefits = [
  { mark: "01", title: "A clear HSK path", copy: "Build a beginner foundation in short, topic-based lessons." },
  { mark: "02", title: "Characters with sound", copy: "See hanzi, pinyin, and meaning together, then hear each phrase aloud." },
  { mark: "03", title: "Practice that remembers", copy: "Review tricky words at a gentle pace with spaced repetition." },
];

export default function HomePage() {
  return <><SiteHeader/><main>
    <section className="relative isolate overflow-hidden"><div className="pointer-events-none absolute inset-0 -z-10 paper-grid opacity-60"/><div className="pointer-events-none absolute -top-10 -right-20 -z-10 size-80 rounded-full bg-[#e8b65a]/15 blur-3xl"/><div className="mx-auto grid max-w-7xl items-center gap-14 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-[1.03fr_.97fr] lg:gap-10 lg:py-28">
      <div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#d5e1d5] bg-white/70 px-3.5 py-2 text-xs font-semibold text-primary shadow-sm"><span className="size-2 rounded-full bg-[#6c9a70]"/>A calmer way to learn Mandarin</div><h1 className="max-w-2xl text-[clamp(3rem,7vw,5.6rem)] leading-[.99] font-semibold tracking-[-0.065em]">Learn Chinese,<br/><span className="text-primary">one lesson</span> at a time.</h1><p className="mt-7 max-w-lg text-base leading-7 text-muted-foreground sm:text-lg sm:leading-8">A friendly, open-source path through beginner Mandarin. Learn useful words, understand the characters, and make a little progress every day.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/register" className="group inline-flex items-center gap-3 rounded-2xl bg-primary px-6 py-4 text-sm font-bold text-primary-foreground shadow-[0_12px_30px_-16px_#245c45] transition hover:-translate-y-0.5 hover:bg-[#1c4b38]">Start learning <span aria-hidden="true" className="text-lg">→</span></Link><Link href="/course" className="inline-flex items-center gap-2 rounded-2xl border border-border bg-card px-6 py-4 text-sm font-semibold transition hover:border-primary/40 hover:bg-white">Explore lessons <span aria-hidden="true">↗</span></Link></div><div className="mt-9 flex items-center gap-4 text-xs text-muted-foreground"><div className="flex -space-x-2"><span className="grid size-8 place-items-center rounded-full border-2 border-background bg-[#e9ddc9]">你</span><span className="grid size-8 place-items-center rounded-full border-2 border-background bg-[#dce7d9]">好</span><span className="grid size-8 place-items-center rounded-full border-2 border-background bg-[#f2dcd0]">学</span></div><span>Built for curious beginners, one small win at a time.</span></div></div>
      <div className="relative mx-auto w-full max-w-[540px]"><div className="absolute -top-5 left-2 z-10 -rotate-6 rounded-xl border border-border bg-card px-4 py-3 shadow-lg"><span className="block text-[10px] font-semibold tracking-[.14em] text-muted-foreground uppercase">today’s phrase</span><span lang="zh" className="hanzi-font text-xl font-semibold">你好</span></div><div className="rounded-[2rem] border border-[#e2e1d8] bg-[#eeede5] p-3 shadow-[0_30px_90px_-50px_#1f3f2d] sm:p-5"><div className="rounded-[1.45rem] border border-border/80 bg-card p-5 sm:p-7"><div className="flex items-center justify-between border-b border-border/80 pb-4"><div><p className="text-[10px] font-bold tracking-[.16em] text-muted-foreground uppercase">HSK 1 · Unit 1</p><h2 className="mt-1 text-sm font-bold">Greetings</h2></div><span className="rounded-full bg-[#eaf0e8] px-3 py-1.5 text-[11px] font-bold text-primary">Lesson 01</span></div><div className="py-8 text-center sm:py-10"><p className="text-xs font-semibold tracking-wide text-muted-foreground">HOW DO YOU SAY “HELLO”?</p><p lang="zh" className="hanzi-font mt-5 text-7xl leading-none font-medium tracking-[.08em] sm:text-8xl">你好</p><p className="mt-4 text-lg tracking-wide text-primary">nǐ hǎo</p><p className="mt-1 text-sm text-muted-foreground">hello · hi</p><button type="button" aria-label="Listen to nǐ hǎo" className="mt-6 inline-flex items-center gap-2 rounded-full border border-border px-4 py-2 text-xs font-semibold text-primary"><span aria-hidden="true">◖))</span>Listen</button></div><div className="rounded-2xl bg-[#f2f1eb] p-4"><div className="flex items-start gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-white text-sm">✦</span><div><p className="text-[10px] font-bold tracking-[.12em] text-muted-foreground uppercase">In a sentence</p><p lang="zh" className="hanzi-font mt-1 text-base">你好，我叫安娜。</p><p className="mt-0.5 text-xs text-muted-foreground">Nǐ hǎo, wǒ jiào Ānnà. · Hello, my name is Anna.</p></div></div></div><div className="mt-5 flex items-center justify-between"><span className="text-xs font-medium text-muted-foreground">Word 1 of 8</span><div className="h-1.5 w-28 overflow-hidden rounded-full bg-[#e5e6df]"><span className="block h-full w-[13%] rounded-full bg-primary"/></div><span className="text-xs font-semibold text-primary">+5 XP</span></div></div></div><div className="absolute -right-1 bottom-8 rotate-3 rounded-2xl border border-[#e1e2d9] bg-white px-4 py-3 shadow-lg sm:-right-8"><span className="block text-[10px] tracking-[.12em] text-muted-foreground uppercase">your pace</span><span className="mt-1 block text-sm font-bold">10 minutes a day <span className="text-[#b65f37]">☀</span></span></div></div>
    </div></section>
    <section className="border-y border-border bg-white/70"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-8 sm:grid-cols-2 sm:px-8 lg:grid-cols-4">{["HSK-based learning path","Hanzi + pinyin together","Listen as you learn","Review words that need it"].map((item,index)=><div key={item} className="flex items-center gap-3 text-sm font-semibold"><span className="grid size-9 place-items-center rounded-xl bg-[#eaf0e8] text-xs font-bold text-primary">0{index+1}</span>{item}</div>)}</div></section>
    <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="max-w-xl"><p className="text-xs font-bold tracking-[.18em] text-accent uppercase">A small, steady rhythm</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Learn the pieces.<br/>Use them right away.</h2><p className="mt-4 leading-7 text-muted-foreground">Each lesson gives you useful words, then helps them stick with quick listening and recall practice.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{benefits.map((item)=><article key={item.mark} className="rounded-3xl border border-border bg-card p-6 sm:p-7"><span className="text-xs font-bold tracking-[.16em] text-accent">{item.mark} / 03</span><h3 className="mt-8 text-xl font-semibold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.copy}</p></article>)}</div></section>
    <section id="learning-path" className="border-y border-border bg-[#eef0e9]"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-18 sm:px-8 sm:py-24 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold tracking-[.18em] text-primary uppercase">Your first stretch</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">A clear path through HSK 1.</h2><p className="mt-4 max-w-md leading-7 text-muted-foreground">Start with greetings, meet new people, count, talk about family, and build everyday habits.</p><Link href="/course" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline">See the learning map →</Link></div><div className="grid gap-3 sm:grid-cols-2">{[{n:"01",t:"Greetings",c:"你好 · 再见"},{n:"02",t:"Introductions",c:"我 · 叫 · 名字"},{n:"03",t:"Numbers & time",c:"一 · 二 · 今天"},{n:"04",t:"Family & people",c:"家 · 爸爸 · 朋友"},{n:"05",t:"Everyday life",c:"吃 · 喝 · 学习"},{n:"06",t:"Food & places",c:"水 · 茶 · 中国"}].map((item)=><div key={item.n} className="flex items-center gap-4 rounded-2xl border border-[#dce1d7] bg-white/80 p-4"><span className="text-xs font-bold text-accent">{item.n}</span><div><h3 className="text-sm font-semibold">{item.t}</h3><p lang="zh" className="hanzi-font mt-1 text-xs text-muted-foreground">{item.c}</p></div><span aria-hidden="true" className="ml-auto text-muted-foreground">↗</span></div>)}</div></div></section>
    <section id="open-source" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-24"><div className="overflow-hidden rounded-[2rem] bg-primary px-7 py-10 text-primary-foreground sm:px-12 sm:py-14"><div className="grid items-center gap-8 md:grid-cols-[1fr_auto]"><div><p className="text-xs font-bold tracking-[.18em] text-white/65 uppercase">Made to grow together</p><h2 className="mt-4 max-w-2xl text-3xl leading-tight font-semibold tracking-tight sm:text-4xl">A learning project that stays open.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-white/75">Explore the curriculum, improve an explanation, or help shape what comes next.</p></div><div className="flex flex-wrap gap-3"><a href="https://github.com/mohammadhussain19/hanzi-journey" target="_blank" rel="noreferrer" className="rounded-xl bg-white px-5 py-3 text-sm font-bold text-primary hover:bg-[#f2f2ec]">View on GitHub ↗</a><Link href="/register" className="rounded-xl border border-white/35 px-5 py-3 text-sm font-semibold hover:bg-white/10">Begin learning</Link></div></div></div></section>
  </main><SiteFooter/></>;
}
